version: '2'
services:
    postgres:
      image: 'postgres:latest'
    redis:
      image: 'redis:latest'
    nginx:
      restart: always
      build: 
        dockerfile: Dockerfile.dev
        context: ./nginx
      ports: 
        - "3050:80"
    server:
      build:
        dockerfile: Dockerfile.dev
        context: ./server
      volumes: 
        - '/app/node_modules'
        - './server:/app'
      ports: 
        - "5000:5000"
      environment: 
        - REDIS_HOST=redis
        - REDIS_PORT=6379
        - PGUSER=postgres
        - PGHOST=postgres
        - PGDATABASE=postgres
        - PGPASSWORD=postgres_password
        - PGPORT=5432
    client:
      build:
        dockerfile: Dockerfile.dev
        context: ./client
      volumes: 
        - '/app/node_modules'
        - './client:/app'
      ports: 
        - "3000:3000"
      environment: 
        - NODE_ENV=development
        - CHOKIDAR_USEPOLLING=true
    worker:
      build:
        dockerfile: Dockerfile.dev
        context: ./worker
      volumes: 
        - '/app/node_modules'
        - './worker:/app'
      environment: 
        - REDIS_HOST=redis
        - REDIS_PORT=6379